title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mohiuddin-zoheb-3256164b/">LinkedIn</a> |
  <a href="https://github.com/Mohiuddin-Zoheb">GitHub</a>
  
  <br>   
  I'm working on Data Science, Computer Vision, Machine learning & NLP related problems.
  I'm also Microsoft Certified Data Scientist Assosiate and also have good knowledge of
  multiple cloud platforms.
  <br>
  </p>



theme: jekyll-theme-minimal
